# Generated by Django 5.0.6 on 2024-07-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='Img',
            field=models.ImageField(default='asd', upload_to='img'),
            preserve_default=False,
        ),
    ]
