# Generated by Django 5.0.6 on 2024-07-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapp', '0002_movies_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='Img',
            field=models.ImageField(upload_to='static/img'),
        ),
    ]
