# Generated by Django 5.0.6 on 2024-07-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapp', '0005_alter_movies_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='Description',
            field=models.TextField(),
        ),
    ]
