# Generated by Django 5.0.6 on 2024-07-04 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapp', '0006_alter_movies_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='Img',
            field=models.ImageField(upload_to='static/Img'),
        ),
    ]
