# Generated by Django 5.0.6 on 2024-07-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapp', '0008_rename_img_movies_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='img',
        ),
        migrations.AddField(
            model_name='movies',
            name='Img',
            field=models.ImageField(default=51, upload_to='img'),
            preserve_default=False,
        ),
    ]
