# Generated by Django 5.0.6 on 2024-07-08 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fapp', '0016_rename_img_movies_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movies',
        ),
    ]
