# Generated by Django 5.0.6 on 2024-07-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fapp', '0017_delete_movies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Year', models.IntegerField()),
                ('Description', models.TextField()),
                ('image', models.ImageField(upload_to='static/img')),
            ],
        ),
    ]
